build: \
	BubbleSynth \
	NoiseTester \
	RingDelaySynth \

.PHONY: BubbleSynth
BubbleSynth:
	$(MAKE) -C BubbleSynth

.PHONY: NoiseTester
NoiseTester:
	$(MAKE) -C NoiseTester

.PHONY: RingDelaySynth
RingDelaySynth:
	$(MAKE) -C RingDelaySynth
