build: \
	BubbleSynth \
	CollidingCombSynth \
	KuramotoModel \
	NoiseTester \
	RingDelaySynth \

.PHONY: BubbleSynth
BubbleSynth:
	$(MAKE) -C BubbleSynth

.PHONY: CollidingCombSynth
CollidingCombSynth:
	$(MAKE) -C CollidingCombSynth

.PHONY: KuramotoModel
KuramotoModel:
	$(MAKE) -C KuramotoModel

.PHONY: NoiseTester
NoiseTester:
	$(MAKE) -C NoiseTester

.PHONY: RingDelaySynth
RingDelaySynth:
	$(MAKE) -C RingDelaySynth
