build: \
	BubbleSynth \
	KSCymbal \
	KuramotoModel \
	NoiseTester \
	RingDelaySynth \

.PHONY: BubbleSynth
BubbleSynth:
	$(MAKE) -C BubbleSynth

.PHONY: KSCymbal
KSCymbal:
	$(MAKE) -C KSCymbal

.PHONY: KuramotoModel
KuramotoModel:
	$(MAKE) -C KuramotoModel

.PHONY: NoiseTester
NoiseTester:
	$(MAKE) -C NoiseTester

.PHONY: RingDelaySynth
RingDelaySynth:
	$(MAKE) -C RingDelaySynth
