# build: \
# 	CV_AudioToCv \
# 	CV_CvToAudio \
# 	CV_ExpADSREnvelope \
# 	CV_ExpPolyADEnvelope \
# 	CV_LinearADSREnvelope \
# 	CV_Multiply \
# 	CV_ParabolicADEnvelope \
# 	CV_PTRSaw \
# 	CV_PTRTrapezoid \
# 	CV_Sin \

build: CV_PTRTrapezoid

.PHONY: CV_AudioToCv
CV_AudioToCv:
	$(MAKE) -C CV_AudioToCv

.PHONY: CV_CvToAudio
CV_CvToAudio:
	$(MAKE) -C CV_CvToAudio

.PHONY: CV_ExpADSREnvelope
CV_ExpADSREnvelope:
	$(MAKE) -C CV_ExpADSREnvelope

.PHONY: CV_ExpPolyADEnvelope
CV_ExpPolyADEnvelope:
	$(MAKE) -C CV_ExpPolyADEnvelope

.PHONY: CV_LinearADSREnvelope
CV_LinearADSREnvelope:
	$(MAKE) -C CV_LinearADSREnvelope

.PHONY: CV_Multiply
CV_Multiply:
	$(MAKE) -C CV_Multiply

.PHONY: CV_ParabolicADEnvelope
CV_ParabolicADEnvelope:
	$(MAKE) -C CV_ParabolicADEnvelope

.PHONY: CV_PTRSaw
CV_PTRSaw:
	$(MAKE) -C CV_PTRSaw

.PHONY: CV_PTRTrapezoid
CV_PTRTrapezoid:
	$(MAKE) -C CV_PTRTrapezoid

.PHONY: CV_Sin
CV_Sin:
	$(MAKE) -C CV_Sin
