build: \
	CV_3PoleLP \
	CV_AudioToCv \
	CV_CvToAudio \
	CV_DelayLP3 \
	CV_DoubleFilter \
	CV_ExpADSREnvelope \
	CV_ExpLoopEnvelope \
	CV_ExpPolyADEnvelope \
  CV_Gate16 \
	CV_HoldFilter \
  CV_Invert \
	CV_LinearADSREnvelope \
	CV_LinearMap \
	CV_Multiply \
	CV_NaiveDelay \
	CV_ParabolicADEnvelope \
	CV_PController \
 	CV_PolyLoopEnvelope \
	CV_PTRSaw \
	CV_PTRTrapezoid \
	CV_RampFilter \
	CV_RateLimiter \
	CV_SchroederAllpass \
	CV_Sin \
  CV_StereoGain \

.PHONY: CV_3PoleLP
CV_3PoleLP:
	$(MAKE) -C CV_3PoleLP

.PHONY: CV_AudioToCv
CV_AudioToCv:
	$(MAKE) -C CV_AudioToCv

.PHONY: CV_CvToAudio
CV_CvToAudio:
	$(MAKE) -C CV_CvToAudio

.PHONY: CV_DelayLP3
CV_DelayLP3:
	$(MAKE) -C CV_DelayLP3

.PHONY: CV_DoubleFilter
CV_DoubleFilter:
	$(MAKE) -C CV_DoubleFilter

.PHONY: CV_ExpADSREnvelope
CV_ExpADSREnvelope:
	$(MAKE) -C CV_ExpADSREnvelope

.PHONY: CV_ExpLoopEnvelope
CV_ExpLoopEnvelope:
	$(MAKE) -C CV_ExpLoopEnvelope

.PHONY: CV_ExpPolyADEnvelope
CV_ExpPolyADEnvelope:
	$(MAKE) -C CV_ExpPolyADEnvelope

.PHONY: CV_Gate16
CV_Gate16:
	$(MAKE) -C CV_Gate16

.PHONY: CV_HoldFilter
CV_HoldFilter:
	$(MAKE) -C CV_HoldFilter

.PHONY: CV_Invert
CV_Invert:
	$(MAKE) -C CV_Invert

.PHONY: CV_LinearADSREnvelope
CV_LinearADSREnvelope:
	$(MAKE) -C CV_LinearADSREnvelope

.PHONY: CV_LinearMap
CV_LinearMap:
	$(MAKE) -C CV_LinearMap

.PHONY: CV_Multiply
CV_Multiply:
	$(MAKE) -C CV_Multiply

.PHONY: CV_NaiveDelay
CV_NaiveDelay:
	$(MAKE) -C CV_NaiveDelay

.PHONY: CV_ParabolicADEnvelope
CV_ParabolicADEnvelope:
	$(MAKE) -C CV_ParabolicADEnvelope

.PHONY: CV_PController
CV_PController:
	$(MAKE) -C CV_PController

.PHONY: CV_PolyLoopEnvelope
CV_PolyLoopEnvelope:
	$(MAKE) -C CV_PolyLoopEnvelope

.PHONY: CV_PTRSaw
CV_PTRSaw:
	$(MAKE) -C CV_PTRSaw

.PHONY: CV_PTRTrapezoid
CV_PTRTrapezoid:
	$(MAKE) -C CV_PTRTrapezoid

.PHONY: CV_RampFilter
CV_RampFilter:
	$(MAKE) -C CV_RampFilter

.PHONY: CV_RateLimiter
CV_RateLimiter:
	$(MAKE) -C CV_RateLimiter

.PHONY: CV_SchroederAllpass
CV_SchroederAllpass:
	$(MAKE) -C CV_SchroederAllpass

.PHONY: CV_Sin
CV_Sin:
	$(MAKE) -C CV_Sin

.PHONY: CV_StereoGain
CV_StereoGain:
	$(MAKE) -C CV_StereoGain
